一、資料結構整理

In [41]:
import pandas as pd
import numpy as np

In [42]:
train_file=pd.read_csv("Final_Train.csv")
train_file

,ID,X01,X02,X03,X04,X05,X06,X07,X08,X09,...,X16,X17,X18,X19,X20,X21,X22,X23,X24,Y
0,1,41.83,124.94,263.22,300.57,10.35,10.39,10.32,90.28,261.76,...,7.37,18.0,3776.31,24.0,0.05,10.35,7.93,78.01,358689.0,3
1,2,41.97,125.30,262.12,300.53,10.33,10.40,10.34,89.50,268.51,...,7.40,18.0,3760.59,24.0,0.00,9.67,7.97,78.08,339139.0,3
2,3,41.90,125.00,261.45,300.29,10.35,10.41,10.33,89.74,263.78,...,7.44,18.0,3754.59,24.0,0.00,9.68,7.98,79.50,326082.0,3
3,4,42.33,125.25,262.12,298.94,10.31,10.41,10.33,89.69,260.09,...,7.47,18.0,3746.73,8.0,5.28,10.92,7.95,80.07,321295.0,3
4,5,42.37,125.03,262.94,301.73,10.33,10.40,10.32,90.20,262.26,...,7.50,18.0,3748.58,8.0,4.60,11.12,7.94,79.96,339248.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20616,20617,40.66,124.73,262.06,300.62,10.65,10.53,11.11,154.49,765.99,...,8.96,32.0,4910.45,9.0,632.11,344.40,7.70,77.49,291896.0,2
20617,20618,43.77,126.15,267.76,304.75,10.64,10.57,11.06,157.19,768.79,...,8.97,32.0,4903.61,9.0,632.89,347.96,7.67,77.98,289563.0,2
20618,20619,41.27,124.20,262.99,300.61,10.65,10.57,11.03,157.85,748.09,...,8.88,32.0,4898.89,9.0,628.78,355.65,7.66,78.58,293656.0,2
20619,20620,41.39,124.99,262.99,298.91,10.68,10.59,11.05,156.53,749.15,...,8.89,32.0,4899.63,9.0,629.43,355.90,7.67,78.62,293181.0,2
20620,20621,42.85,125.39,266.16,302.25,10.66,10.56,11.08,154.45,763.38,...,8.83,32.0,4888.82,9.0,631.65,279.31,7.65,79.01,292206.0,3

In [43]:
test_file=pd.read_csv("Final_Test.csv")
test_file

,ID,X01,X02,X03,X04,X05,X06,X07,X08,X09,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,X24
0,1,41.61,124.91,262.32,300.96,10.36,10.40,10.33,93.21,268.58,...,6416.88,7.32,18.0,3605.31,8.0,114.12,26.99,7.94,79.36,314391.0
1,2,40.98,125.06,259.96,297.68,10.36,10.42,10.33,86.64,261.86,...,6398.13,7.20,18.0,3574.34,30.0,0.00,18.96,7.93,77.41,308945.0
2,3,41.55,124.87,261.75,299.36,10.34,10.40,10.33,88.41,270.73,...,6396.88,7.27,18.0,3542.92,30.0,0.00,19.77,7.95,79.74,301684.0
3,4,41.72,124.96,261.59,297.80,10.34,10.38,10.33,86.41,282.72,...,6417.50,8.04,18.0,3436.62,10.0,832.15,40.83,7.91,88.66,287037.0
4,5,42.87,125.09,264.50,302.26,10.36,10.23,10.47,90.97,279.16,...,6437.50,7.68,22.0,4225.99,13.0,1232.97,6.19,7.84,82.65,308094.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,41.93,125.54,265.21,301.49,10.68,10.42,11.07,151.99,811.54,...,5915.25,9.32,42.0,4118.58,8.0,502.86,267.07,7.53,77.24,294344.0
496,497,41.08,124.83,263.59,300.03,10.62,10.41,11.05,153.01,809.94,...,5917.88,9.28,42.0,4110.08,20.0,1091.41,238.38,7.57,80.42,295670.0
497,498,41.61,124.85,264.60,300.65,10.66,10.42,11.07,166.14,678.14,...,5931.38,8.52,32.0,5154.47,11.0,900.89,27.45,7.64,77.52,292249.0
498,499,41.97,125.13,265.30,302.42,10.65,10.40,11.07,159.18,751.17,...,5907.25,8.76,32.0,5054.18,7.0,288.92,251.37,7.62,78.14,289418.0
499,500,41.05,125.10,261.79,290.63,10.65,10.55,11.05,158.30,776.94,...,5930.75,9.07,32.0,4964.61,6.0,300.52,289.78,7.51,78.77,294423.0

In [44]:
train_file['ID'][0] in test_file['ID']

True

In [45]:
train_file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20621 entries, 0 to 20620
Data columns (total 26 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      20621 non-null  int64
 1   X01     20621 non-null  float64
 2   X02     20621 non-null  float64
 3   X03     20621 non-null  float64
 4   X04     20621 non-null  float64
 5   X05     20621 non-null  float64
 6   X06     20621 non-null  float64
 7   X07     20621 non-null  float64
 8   X08     20621 non-null  float64
 9   X09     20621 non-null  float64
 10  X10     20621 non-null  float64
 11  X11     20621 non-null  float64
 12  X12     20621 non-null  float64
 13  X13     20621 non-null  float64
 14  X14     20621 non-null  float64
 15  X15     20621 non-null  float64
 16  X16     20621 non-null  float64
 17  X17     20621 non-null  float64
 18  X18     20621 non-null  float64
 19  X19     20621 non-null  float64
 20  X20     20621 non-null  float64
 21  X21     20621 non-null  float64
 22  X22     20621 non-null  float64
 23  X23     20621 non-null  float64
 24  X24     20621 non-null  float64
 25  Y       20621 non-null  int64
dtypes: float64(24), int64(2)
memory usage: 4.1 MB

In [46]:
test_file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 25 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      500 non-null    int64
 1   X01     500 non-null    float64
 2   X02     500 non-null    float64
 3   X03     500 non-null    float64
 4   X04     500 non-null    float64
 5   X05     500 non-null    float64
 6   X06     500 non-null    float64
 7   X07     500 non-null    float64
 8   X08     500 non-null    float64
 9   X09     500 non-null    float64
 10  X10     500 non-null    float64
 11  X11     500 non-null    float64
 12  X12     500 non-null    float64
 13  X13     500 non-null    float64
 14  X14     500 non-null    float64
 15  X15     500 non-null    float64
 16  X16     500 non-null    float64
 17  X17     500 non-null    float64
 18  X18     500 non-null    float64
 19  X19     500 non-null    float64
 20  X20     500 non-null    float64
 21  X21     500 non-null    float64
 22  X22     500 non-null    float64
 23  X23     500 non-null    float64
 24  X24     500 non-null    float64
dtypes: float64(24), int64(1)
memory usage: 97.8 KB

In [47]:
train_ans=train_file['Y']
train_info=train_file.drop(columns=['Y'],axis=1)

In [48]:
train_info

,ID,X01,X02,X03,X04,X05,X06,X07,X08,X09,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,X24
0,1,41.83,124.94,263.22,300.57,10.35,10.39,10.32,90.28,261.76,...,6407.50,7.37,18.0,3776.31,24.0,0.05,10.35,7.93,78.01,358689.0
1,2,41.97,125.30,262.12,300.53,10.33,10.40,10.34,89.50,268.51,...,6417.50,7.40,18.0,3760.59,24.0,0.00,9.67,7.97,78.08,339139.0
2,3,41.90,125.00,261.45,300.29,10.35,10.41,10.33,89.74,263.78,...,6405.00,7.44,18.0,3754.59,24.0,0.00,9.68,7.98,79.50,326082.0
3,4,42.33,125.25,262.12,298.94,10.31,10.41,10.33,89.69,260.09,...,6427.50,7.47,18.0,3746.73,8.0,5.28,10.92,7.95,80.07,321295.0
4,5,42.37,125.03,262.94,301.73,10.33,10.40,10.32,90.20,262.26,...,6400.00,7.50,18.0,3748.58,8.0,4.60,11.12,7.94,79.96,339248.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20616,20617,40.66,124.73,262.06,300.62,10.65,10.53,11.11,154.49,765.99,...,5911.38,8.96,32.0,4910.45,9.0,632.11,344.40,7.70,77.49,291896.0
20617,20618,43.77,126.15,267.76,304.75,10.64,10.57,11.06,157.19,768.79,...,5887.13,8.97,32.0,4903.61,9.0,632.89,347.96,7.67,77.98,289563.0
20618,20619,41.27,124.20,262.99,300.61,10.65,10.57,11.03,157.85,748.09,...,5898.88,8.88,32.0,4898.89,9.0,628.78,355.65,7.66,78.58,293656.0
20619,20620,41.39,124.99,262.99,298.91,10.68,10.59,11.05,156.53,749.15,...,5913.63,8.89,32.0,4899.63,9.0,629.43,355.90,7.67,78.62,293181.0
20620,20621,42.85,125.39,266.16,302.25,10.66,10.56,11.08,154.45,763.38,...,5900.00,8.83,32.0,4888.82,9.0,631.65,279.31,7.65,79.01,292206.0

In [49]:
predict=pd.DataFrame(data=test_file['ID'],columns=['ID'])
predict_data1=predict.merge(test_file,how='left',on='ID')
predict_data1

,ID,X01,X02,X03,X04,X05,X06,X07,X08,X09,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,X24
0,1,41.61,124.91,262.32,300.96,10.36,10.40,10.33,93.21,268.58,...,6416.88,7.32,18.0,3605.31,8.0,114.12,26.99,7.94,79.36,314391.0
1,2,40.98,125.06,259.96,297.68,10.36,10.42,10.33,86.64,261.86,...,6398.13,7.20,18.0,3574.34,30.0,0.00,18.96,7.93,77.41,308945.0
2,3,41.55,124.87,261.75,299.36,10.34,10.40,10.33,88.41,270.73,...,6396.88,7.27,18.0,3542.92,30.0,0.00,19.77,7.95,79.74,301684.0
3,4,41.72,124.96,261.59,297.80,10.34,10.38,10.33,86.41,282.72,...,6417.50,8.04,18.0,3436.62,10.0,832.15,40.83,7.91,88.66,287037.0
4,5,42.87,125.09,264.50,302.26,10.36,10.23,10.47,90.97,279.16,...,6437.50,7.68,22.0,4225.99,13.0,1232.97,6.19,7.84,82.65,308094.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,41.93,125.54,265.21,301.49,10.68,10.42,11.07,151.99,811.54,...,5915.25,9.32,42.0,4118.58,8.0,502.86,267.07,7.53,77.24,294344.0
496,497,41.08,124.83,263.59,300.03,10.62,10.41,11.05,153.01,809.94,...,5917.88,9.28,42.0,4110.08,20.0,1091.41,238.38,7.57,80.42,295670.0
497,498,41.61,124.85,264.60,300.65,10.66,10.42,11.07,166.14,678.14,...,5931.38,8.52,32.0,5154.47,11.0,900.89,27.45,7.64,77.52,292249.0
498,499,41.97,125.13,265.30,302.42,10.65,10.40,11.07,159.18,751.17,...,5907.25,8.76,32.0,5054.18,7.0,288.92,251.37,7.62,78.14,289418.0
499,500,41.05,125.10,261.79,290.63,10.65,10.55,11.05,158.30,776.94,...,5930.75,9.07,32.0,4964.61,6.0,300.52,289.78,7.51,78.77,294423.0

二、正規化

In [50]:
def normalize(data):
    from sklearn.preprocessing import MinMaxScaler
    scaler = MinMaxScaler()
    scaler.fit(data)
    data[data.columns] = scaler.fit_transform(data[data.columns].to_numpy()) 
    return data

In [51]:
x_train=normalize(train_info)
x_train

c:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(

,ID,X01,X02,X03,X04,X05,X06,X07,X08,X09,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,X24
0,0.000000,0.713478,0.532026,0.865780,0.599378,0.376884,0.429224,0.881298,0.044409,0.143344,...,0.483142,0.160523,0.18,0.299767,0.48,0.000027,0.006539,0.144890,0.223941,0.644043
1,0.000048,0.720075,0.579085,0.859446,0.598881,0.366834,0.433790,0.883006,0.040159,0.152700,...,0.490203,0.161178,0.18,0.296287,0.48,0.000000,0.006103,0.147477,0.224145,0.608430
2,0.000097,0.716777,0.539869,0.855588,0.595896,0.376884,0.438356,0.882152,0.041467,0.146144,...,0.481377,0.162050,0.18,0.294959,0.48,0.000000,0.006110,0.148124,0.228283,0.584645
3,0.000145,0.737041,0.572549,0.859446,0.579104,0.356784,0.438356,0.882152,0.041194,0.141030,...,0.497264,0.162704,0.18,0.293219,0.16,0.002893,0.006904,0.146184,0.229944,0.575925
4,0.000194,0.738926,0.543791,0.864168,0.613806,0.366834,0.433790,0.881298,0.043973,0.144037,...,0.477846,0.163359,0.18,0.293628,0.16,0.002521,0.007033,0.145537,0.229624,0.608629
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20616,0.999806,0.658341,0.504575,0.859101,0.600000,0.527638,0.493151,0.948762,0.394289,0.842227,...,0.132837,0.195202,0.32,0.550852,0.18,0.346369,0.220693,0.130013,0.222426,0.522371
20617,0.999855,0.804901,0.690196,0.891921,0.651368,0.522613,0.511416,0.944492,0.409002,0.846108,...,0.115714,0.195420,0.32,0.549337,0.18,0.346797,0.222975,0.128072,0.223854,0.518121
20618,0.999903,0.687088,0.435294,0.864456,0.599876,0.527638,0.511416,0.941930,0.412598,0.817417,...,0.124011,0.193457,0.32,0.548292,0.18,0.344545,0.227905,0.127426,0.225602,0.525577
20619,0.999952,0.692743,0.538562,0.864456,0.578731,0.542714,0.520548,0.943638,0.405405,0.818886,...,0.134425,0.193675,0.32,0.548456,0.18,0.344901,0.228065,0.128072,0.225719,0.524712
20620,1.000000,0.761546,0.590850,0.882709,0.620274,0.532663,0.506849,0.946200,0.394071,0.838610,...,0.124801,0.192366,0.32,0.546063,0.18,0.346117,0.178965,0.126779,0.226855,0.522936

In [52]:
from sklearn.preprocessing import MinMaxScaler
train_ans1 = MinMaxScaler().fit(train_ans.values.reshape(-1,1))
train_ans2 = MinMaxScaler().fit_transform(train_ans.values.reshape(-1,1))
train_ans3=np.ravel(train_ans2)
train_ans3

array([0.5 , 0.5 , 0.5 , ..., 0.25, 0.25, 0.5 ])

In [53]:
predict_data2=normalize(predict_data1)
predict_data2

c:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(

,ID,X01,X02,X03,X04,X05,X06,X07,X08,X09,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,X24
0,0.000000,0.764706,0.438559,0.923221,0.603159,0.567568,0.552239,0.123188,0.072690,0.148606,...,0.756628,0.281972,0.346154,0.175697,0.205128,0.062538,0.026233,0.631250,0.714800,0.654255
1,0.002004,0.730392,0.470339,0.908513,0.520933,0.567568,0.567164,0.123188,0.030201,0.138504,...,0.734287,0.263482,0.346154,0.167793,0.769231,0.000000,0.017254,0.628125,0.694141,0.642738
2,0.004008,0.761438,0.430085,0.919668,0.563048,0.549550,0.552239,0.123188,0.041648,0.151838,...,0.732797,0.274268,0.346154,0.159774,0.769231,0.000000,0.018160,0.634375,0.718826,0.627382
3,0.006012,0.770697,0.449153,0.918671,0.523941,0.549550,0.537313,0.123188,0.028714,0.169861,...,0.757367,0.392912,0.346154,0.132645,0.256410,0.456020,0.041709,0.621875,0.813328,0.596407
4,0.008016,0.833333,0.476695,0.936807,0.635748,0.567568,0.425373,0.224638,0.058203,0.164510,...,0.781197,0.337442,0.423077,0.334103,0.333333,0.675670,0.002974,0.600000,0.749656,0.640938
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,0.991984,0.782135,0.572034,0.941231,0.616445,0.855856,0.567164,0.659420,0.452823,0.964780,...,0.158916,0.590139,0.807692,0.306691,0.205128,0.275568,0.294692,0.503125,0.692340,0.611860
496,0.993988,0.735839,0.421610,0.931135,0.579845,0.801802,0.559701,0.644928,0.459419,0.962375,...,0.162049,0.583975,0.807692,0.304521,0.512821,0.598095,0.262611,0.515625,0.726030,0.614664
497,0.995992,0.764706,0.425847,0.937430,0.595387,0.837838,0.567164,0.659420,0.544332,0.764254,...,0.178135,0.466872,0.615385,0.571064,0.282051,0.493690,0.026747,0.537500,0.695307,0.607429
498,0.997996,0.784314,0.485169,0.941792,0.639759,0.828829,0.552239,0.659420,0.499321,0.874032,...,0.149383,0.503852,0.615385,0.545469,0.179487,0.158329,0.277136,0.531250,0.701875,0.601442
499,1.000000,0.734205,0.478814,0.919918,0.344197,0.828829,0.664179,0.644928,0.493630,0.912770,...,0.177385,0.551618,0.615385,0.522609,0.153846,0.164686,0.320086,0.496875,0.708550,0.612027

In [54]:
predict_data3=predict_data2.drop(columns=['ID'],axis=1)
predict_data3

,X01,X02,X03,X04,X05,X06,X07,X08,X09,X10,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,X24
0,0.764706,0.438559,0.923221,0.603159,0.567568,0.552239,0.123188,0.072690,0.148606,0.233793,...,0.756628,0.281972,0.346154,0.175697,0.205128,0.062538,0.026233,0.631250,0.714800,0.654255
1,0.730392,0.470339,0.908513,0.520933,0.567568,0.567164,0.123188,0.030201,0.138504,0.184901,...,0.734287,0.263482,0.346154,0.167793,0.769231,0.000000,0.017254,0.628125,0.694141,0.642738
2,0.761438,0.430085,0.919668,0.563048,0.549550,0.552239,0.123188,0.041648,0.151838,0.189335,...,0.732797,0.274268,0.346154,0.159774,0.769231,0.000000,0.018160,0.634375,0.718826,0.627382
3,0.770697,0.449153,0.918671,0.523941,0.549550,0.537313,0.123188,0.028714,0.169861,0.206111,...,0.757367,0.392912,0.346154,0.132645,0.256410,0.456020,0.041709,0.621875,0.813328,0.596407
4,0.833333,0.476695,0.936807,0.635748,0.567568,0.425373,0.224638,0.058203,0.164510,0.259557,...,0.781197,0.337442,0.423077,0.334103,0.333333,0.675670,0.002974,0.600000,0.749656,0.640938
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,0.782135,0.572034,0.941231,0.616445,0.855856,0.567164,0.659420,0.452823,0.964780,0.187058,...,0.158916,0.590139,0.807692,0.306691,0.205128,0.275568,0.294692,0.503125,0.692340,0.611860
496,0.735839,0.421610,0.931135,0.579845,0.801802,0.559701,0.644928,0.459419,0.962375,0.276932,...,0.162049,0.583975,0.807692,0.304521,0.512821,0.598095,0.262611,0.515625,0.726030,0.614664
497,0.764706,0.425847,0.937430,0.595387,0.837838,0.567164,0.659420,0.544332,0.764254,0.213062,...,0.178135,0.466872,0.615385,0.571064,0.282051,0.493690,0.026747,0.537500,0.695307,0.607429
498,0.784314,0.485169,0.941792,0.639759,0.828829,0.552239,0.659420,0.499321,0.874032,0.366087,...,0.149383,0.503852,0.615385,0.545469,0.179487,0.158329,0.277136,0.531250,0.701875,0.601442
499,0.734205,0.478814,0.919918,0.344197,0.828829,0.664179,0.644928,0.493630,0.912770,0.351228,...,0.177385,0.551618,0.615385,0.522609,0.153846,0.164686,0.320086,0.496875,0.708550,0.612027

In [55]:
X_train=x_train.drop(columns=['ID'],axis=1)
X_train

,X01,X02,X03,X04,X05,X06,X07,X08,X09,X10,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,X24
0,0.713478,0.532026,0.865780,0.599378,0.376884,0.429224,0.881298,0.044409,0.143344,0.136743,...,0.483142,0.160523,0.18,0.299767,0.48,0.000027,0.006539,0.144890,0.223941,0.644043
1,0.720075,0.579085,0.859446,0.598881,0.366834,0.433790,0.883006,0.040159,0.152700,0.137630,...,0.490203,0.161178,0.18,0.296287,0.48,0.000000,0.006103,0.147477,0.224145,0.608430
2,0.716777,0.539869,0.855588,0.595896,0.376884,0.438356,0.882152,0.041467,0.146144,0.130904,...,0.481377,0.162050,0.18,0.294959,0.48,0.000000,0.006110,0.148124,0.228283,0.584645
3,0.737041,0.572549,0.859446,0.579104,0.356784,0.438356,0.882152,0.041194,0.141030,0.141326,...,0.497264,0.162704,0.18,0.293219,0.16,0.002893,0.006904,0.146184,0.229944,0.575925
4,0.738926,0.543791,0.864168,0.613806,0.366834,0.433790,0.881298,0.043973,0.144037,0.249168,...,0.477846,0.163359,0.18,0.293628,0.16,0.002521,0.007033,0.145537,0.229624,0.608629
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20616,0.658341,0.504575,0.859101,0.600000,0.527638,0.493151,0.948762,0.394289,0.842227,0.213024,...,0.132837,0.195202,0.32,0.550852,0.18,0.346369,0.220693,0.130013,0.222426,0.522371
20617,0.804901,0.690196,0.891921,0.651368,0.522613,0.511416,0.944492,0.409002,0.846108,0.213467,...,0.115714,0.195420,0.32,0.549337,0.18,0.346797,0.222975,0.128072,0.223854,0.518121
20618,0.687088,0.435294,0.864456,0.599876,0.527638,0.511416,0.941930,0.412598,0.817417,0.210289,...,0.124011,0.193457,0.32,0.548292,0.18,0.344545,0.227905,0.127426,0.225602,0.525577
20619,0.692743,0.538562,0.864456,0.578731,0.542714,0.520548,0.943638,0.405405,0.818886,0.182571,...,0.134425,0.193675,0.32,0.548456,0.18,0.344901,0.228065,0.128072,0.225719,0.524712
20620,0.761546,0.590850,0.882709,0.620274,0.532663,0.506849,0.946200,0.394071,0.838610,0.228177,...,0.124801,0.192366,0.32,0.546063,0.18,0.346117,0.178965,0.126779,0.226855,0.522936

三、多層感知器

In [56]:
from sklearn.neural_network import MLPRegressor
mlp=MLPRegressor(random_state=1).fit(X_train,train_ans3)
mlp_pred=mlp.predict(X_train)

In [57]:
mlp_y_pred=mlp.predict(predict_data3)

In [58]:
#MLP的預測結果
mlp_output=pd.DataFrame()
mlp_output['ID']=test_file['ID']
mlp_output['C1']=mlp_y_pred
mlp_output['C2']=mlp_y_pred
mlp_output['C3']=mlp_y_pred
mlp_output['C4']=mlp_y_pred
mlp_output['C5']=mlp_y_pred
mlp_output

      ID        C1        C2        C3        C4        C5
0      1  0.308293  0.308293  0.308293  0.308293  0.308293
1      2  0.647493  0.647493  0.647493  0.647493  0.647493
2      3  0.641988  0.641988  0.641988  0.641988  0.641988
3      4  0.279526  0.279526  0.279526  0.279526  0.279526
4      5  0.290854  0.290854  0.290854  0.290854  0.290854
..   ...       ...       ...       ...       ...       ...
495  496  0.088180  0.088180  0.088180  0.088180  0.088180
496  497  0.061410  0.061410  0.061410  0.061410  0.061410
497  498 -0.027055 -0.027055 -0.027055 -0.027055 -0.027055
498  499  0.061081  0.061081  0.061081  0.061081  0.061081
499  500 -0.021145 -0.021145 -0.021145 -0.021145 -0.021145

[500 rows x 6 columns]

In [59]:
mlp_output.to_csv("mlp_result.csv",index=False)

四、隨機森林

In [60]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor(n_estimators=1000,max_features='auto',n_jobs=-1,oob_score=True,bootstrap=True,random_state=1)
rf.fit(X_train,train_ans3)
rf_pred=rf.predict(X_train)

c:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [61]:
rf_y_pred=rf.predict(predict_data3)

In [62]:
#rf的預測結果
rf_output=pd.DataFrame()
rf_output['ID']=test_file['ID']
rf_output['C1']=rf_y_pred
rf_output['C2']=rf_y_pred
rf_output['C3']=rf_y_pred
rf_output['C4']=rf_y_pred
rf_output['C5']=rf_y_pred
rf_output

      ID       C1       C2       C3       C4       C5
0      1  0.39625  0.39625  0.39625  0.39625  0.39625
1      2  0.54575  0.54575  0.54575  0.54575  0.54575
2      3  0.54125  0.54125  0.54125  0.54125  0.54125
3      4  0.48275  0.48275  0.48275  0.48275  0.48275
4      5  0.49150  0.49150  0.49150  0.49150  0.49150
..   ...      ...      ...      ...      ...      ...
495  496  0.26625  0.26625  0.26625  0.26625  0.26625
496  497  0.24800  0.24800  0.24800  0.24800  0.24800
497  498  0.17100  0.17100  0.17100  0.17100  0.17100
498  499  0.27725  0.27725  0.27725  0.27725  0.27725
499  500  0.28925  0.28925  0.28925  0.28925  0.28925

[500 rows x 6 columns]

In [63]:
rf_output.to_csv("rf_result.csv",index=False)

五、KNN

In [64]:
from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor().fit(X_train,train_ans3)
knn_pred=knn.predict(X_train)

c:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(

In [65]:
knn_y_pred=knn.predict(predict_data3)

c:\Users\ASUS\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(

In [66]:
#XGBoost的預測結果
knn_output=pd.DataFrame()
knn_output['ID']=test_file['ID']
knn_output['C1']=knn_y_pred
knn_output['C2']=knn_y_pred
knn_output['C3']=knn_y_pred
knn_output['C4']=knn_y_pred
knn_output['C5']=knn_y_pred
knn_output

      ID    C1    C2    C3    C4    C5
0      1  0.40  0.40  0.40  0.40  0.40
1      2  0.75  0.75  0.75  0.75  0.75
2      3  0.75  0.75  0.75  0.75  0.75
3      4  0.50  0.50  0.50  0.50  0.50
4      5  0.65  0.65  0.65  0.65  0.65
..   ...   ...   ...   ...   ...   ...
495  496  0.45  0.45  0.45  0.45  0.45
496  497  0.25  0.25  0.25  0.25  0.25
497  498  0.05  0.05  0.05  0.05  0.05
498  499  0.15  0.15  0.15  0.15  0.15
499  500  0.40  0.40  0.40  0.40  0.40

[500 rows x 6 columns]

In [67]:
knn_output.to_csv("knn_result.csv",index=False)

六、支援向量機

In [68]:
from sklearn.svm import SVR
svm=SVR().fit(X_train,train_ans3)
svm_pred=svm.predict(X_train)

In [69]:
svm_y_pred=svm.predict(predict_data3)

In [70]:
#svm的預測結果
svm_output=pd.DataFrame()
svm_output['ID']=test_file['ID']
svm_output['C1']=svm_y_pred
svm_output['C2']=svm_y_pred
svm_output['C3']=svm_y_pred
svm_output['C4']=svm_y_pred
svm_output['C5']=svm_y_pred
svm_output

      ID        C1        C2        C3        C4        C5
0      1  0.248828  0.248828  0.248828  0.248828  0.248828
1      2  0.485997  0.485997  0.485997  0.485997  0.485997
2      3  0.479505  0.479505  0.479505  0.479505  0.479505
3      4  0.331250  0.331250  0.331250  0.331250  0.331250
4      5  0.374506  0.374506  0.374506  0.374506  0.374506
..   ...       ...       ...       ...       ...       ...
495  496 -0.421213 -0.421213 -0.421213 -0.421213 -0.421213
496  497 -0.310931 -0.310931 -0.310931 -0.310931 -0.310931
497  498 -0.500976 -0.500976 -0.500976 -0.500976 -0.500976
498  499 -0.505806 -0.505806 -0.505806 -0.505806 -0.505806
499  500 -0.530533 -0.530533 -0.530533 -0.530533 -0.530533

[500 rows x 6 columns]

In [71]:
svm_output.to_csv("svm_result.csv",index=False)

七、績效評估(Logloss)

In [72]:
def logloss(y_true, y_pred, eps=1e-15):
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    assert (len(y_true) and len(y_true) == len(y_pred))
    p = np.clip(y_pred, eps, 1-eps)
    loss = np.sum(- y_true * np.log(p) - (1 - y_true) * np.log(1-p))
    return loss / len(y_true)

In [73]:
print('多層感知器的logloss:',logloss(train_ans3,mlp_pred))

多層感知器的logloss: 0.5265059956731725

In [74]:
print('隨機森林的logloss:',logloss(train_ans3,rf_pred))

隨機森林的logloss: 0.40195772537514823

In [78]:
print('KNN的logloss:',logloss(train_ans3,knn_pred))

KNN的logloss: 0.4550091656681401

In [76]:
print('支援向量機的logloss:',logloss(train_ans3,svm_pred))

支援向量機的logloss: 0.5178599500093699

In [77]:
rf_output.to_csv("fdg_預測結果.csv",index=False,encoding='utf-8-sig')